apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  type: NodePort
  selector:
    app: web
  ports:
    - nodePort: 31479   # Port used for acceptingn request from Public CLients
      port: 8080 #Private Internal Port used by Nodes
      targetPort: 9087 # COntainer Port